services:
  db:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: gymbrosdb
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
          interval: 10s
          retries: 5
          start_period: 10s

  web:
    image: vcandel/gymbrosdb:latest
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gymbrosdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      db:
        condition: service_healthy

    restart: on-failure

volumes:
  db_data:

