services:
  db:
    image: mysql:9.2
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: gymbrosdb
      MYSQL_ROOT_PASSWORD: pass
    ports:
     - "3306:3306"
    volumes:
     - ~/mysql_data:/var/lib/mysql
    restart: unless-stopped